server:
  port: 8010

spring:
  application:
    name: account-service
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: '000000'
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: localhost:8888
      #        client-ip: 192.168.0.108
      # 取消延迟加载
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-sentinel-flow
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: flow
            username: nacos
            password: nacos
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/cloud-alibaba?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: tqz123456789.
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

security:
  oauth2:
    resource:
      id: account-service
      user-info-uri: http://localhost:8070/user/current/get

logging:
  level:
    root: info
    org.springframework.security: debug

## swagger自定义配置属性
tqz:
  swagger:
    enabled: true
    title: account-service在线接口平台
    description: account-service微服务相关接口


rocketmq:
  name-server: 172.31.0.44:9876
  producer:
    group: cloud-group

seata:
  enabled: false
  application-id: ${spring.application.name}
  tx-service-group: account_service_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      serverAddr: localhost:8848
      namespace: public
      group: SEATA_GROUP
      userName: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      namespace: public
      group: SEATA_GROUP
      userName: nacos
      password: nacos
      cluster: default