server:
  port: 8021

spring:
  main:
    allow-circular-references: true # Spring Boot 2.6.0版本开始默认禁止循环依赖
  application:
    name: product-service
  security:
    user:
      name: admin
      password: 111111
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.0.3:8848
        username: nacos
        password: nacos
        namespace: public
    sentinel:
      filter:
        enabled: true # sentinel在web环境下开启拦截器
      transport:
        dashboard: localhost:8888
      #        client-ip: 192.168.0.108
      # 取消延迟加载
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: 172.17.0.3:8848
            data-id: ${spring.application.name}-sentinel-flow
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: flow
            username: nacos
            password: nacos
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.17.0.2:3306/cloud-alibaba?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

### Mybatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

### OAuth2.0
security:
  oauth2:
    resource:
      id: product-service
      loadBalanced: true # 调用获取用户接口的时候是否需要使用负载均衡，true的话表示需要，并且 user-info-uri 需要使用服务名
      #user-info-uri: http://auth-service/auth/user/current/get

# 指定日志级别
logging:
  level:
    com.alibaba.nacos: error
    org.apache.rocketmq.remoting.common: error
  config: classpath:logback-custom.xml

### Seata分布式事务配置
seata:
  enabled: true # Seata开关，默认开启
  application-id: ${spring.application.name}
  tx-service-group: product_service_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      # namespace: public # Nacos配置中心的命名空间如果使用 public 则不能指定，否则会拉取不到配置
      serverAddr: 172.17.0.3:8848
      group: SEATA_GROUP
      userName: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 172.17.0.3:8848
      namespace: public
      userName: nacos
      password: nacos
      cluster: default

### Dubbo 配置
dubbo:
  application:
    name: ${spring.application.name}
  scan:
    base-packages: com.tqz.alibaba.cloud.product.dubbo
  protocol:
    name: dubbo
    port: 21821
  registry:
    address: spring-cloud://localhost
    check: false
  consumer:
    check: false
  cloud:
    subscribed-services: order-service

## swagger自定义配置属性
tqz:
  swagger:
    enabled: true
    title: product-service在线接口平台
    description: product-service微服务相关接口