server:
  port: 8011

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: 111111
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.0.3:8848
        username: nacos
        password: nacos
        namespace: public

    sentinel:
      filter:
        enabled: true # sentinel在web环境下开启拦截器
      transport:
        dashboard: localhost:8888
      #        client-ip: 192.168.0.108
      # 取消延迟加载
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: 172.17.0.3:8848
            data-id: ${spring.application.name}-sentinel-flow
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: flow
            username: nacos
            password: nacos
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.17.0.2:3306/cloud-alibaba?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: tqz123456789.
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

security:
  oauth2:
    resource:
      id: account-service
      loadBalanced: true # 调用获取用户接口的时候是否需要使用负载均衡，true的话表示需要，并且 user-info-uri 需要使用服务名
      user-info-uri: http://auth-service/user/current/get

logging:
  level:
    root: info
    org.springframework.security: debug

### RocketMQ配置
rocketmq:
  name-server: 172.31.0.44:9876
  producer:
    group: cloud-group

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: account_service_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      serverAddr: 172.17.0.3:8848
      # namespace: public
      group: SEATA_GROUP
      userName: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 172.17.0.3:8848
      namespace: public
      group: SEATA_GROUP
      userName: nacos
      password: nacos
      cluster: default

## swagger自定义配置属性
tqz:
  swagger:
    enabled: true
    title: account-service在线接口平台
    description: account-service微服务相关接口